### ISSUE TITLE
Issue JWT Tokens in /api/me

### ISSUE THREAD

**Issue by hillcrestpaul0719** [wlmac/metropolis#109]
It may be a good idea to allow logged in users to issue a JWT token for themselves without sending their login credentials again

**Comment by ApocalypseCalculator** [comment]
Does this not allow CSRF attacks since the returned information is based on session id cookie?

**Comment by nyiyui** [comment]
I think the current system works fine (enough). Plus, issuing a harder-to-revoke JWT refresh token just a session token is a bit sus.

**Comment by JasonLovesDoggo** [comment]
Closed for the time being. Subjected to being reopened.
