### ISSUE TITLE
URL Shortener

### ISSUE THREAD

**Issue by nyiyui** [wlmac/metropolis#111]

**Comment by nyiyui** [comment]
Probably not for now; there doesn't seem to be a wide/large need for it

**Comment by JasonLovesDoggo** [comment]
+ cost of a domain. 
 
 URI's are not that long for mld so only real improvement would be a mld.ca style domain but there is no need.

**Comment by nyiyui** [comment]
Yeah, (but for internal ones we can just add via server config). (Also,
domains cost less than a few dollars a year if done well.)

**Comment by JasonLovesDoggo** [comment]
yeah I pay 10> for mine but it's still unwanted/needed
