### ISSUE TITLE
Announcement approval email delayed sending for 6+ hours

### ISSUE THREAD

**Issue by skyflaren** [wlmac/metropolis#133]
![image](https://user-images.githubusercontent.com/45515570/140845860-2c52a640-d32f-4add-a6c9-d32fd7effd43.png)

---

![image](https://user-images.githubusercontent.com/45515570/140845907-511773df-2c98-44f7-9393-2de965c277bc.png)

**Comment by JasonLovesDoggo** [comment]
Can't seem to replicate
