### ISSUE TITLE
Remember Me Isn't Working

### ISSUE THREAD

**Issue by nyiyui** [wlmac/metropolis#160]
logged out whenver the network is changed and there is a new session (maybe only app) when rememberme option is used

**Comment by JasonLovesDoggo** [comment]
not sure but it doesn't seem like the option is used on the site
https://github.com/wlmac/metropolis/blob/ffa9b76128132a038a6e9467bc0aa84ac7d535f1/templates/account/login.html#L59

**Comment by JasonLovesDoggo** [comment]
after a closer look it seems like set_expiry(0) deletes the cookie on session end, I will write a custom login class to fix this.
https://docs.djangoproject.com/en/4.1/topics/http/sessions/#django.contrib.sessions.backends.base.SessionBase.set_expiry

**Comment by nyiyui** [comment]
Oh, that's interesting…I guess I should read the docs…
Maybe we can just set expiry to e.g. 1 year instead of making a subclass

**Comment by JasonLovesDoggo** [comment]
> .g. 1 year instead of making a subclass we 
we 100% could I'm just not sure what else SESSION_COOKIE_AGE effects so I didn't wan't to mess anything up but I can just revert the commit and do that

**Comment by JasonLovesDoggo** [comment]
Fixed.
