### ISSUE TITLE
api: 500 when invalid JWT is used

### ISSUE THREAD

**Issue by nyiyui** [wlmac/metropolis#205]
When an invalid (malformed) JWT is used in the `Authentication` header in API requests, an HTTP 500 error is returned (there is an exception raised somewhere).

**Comment by JasonLovesDoggo** [comment]
fixed via  a2bfe40e288c14546dd6ffa559acd45d030c2049 ( however will leave it for April/Daisy )

**Comment by wither-rose** [comment]
It has been fixed now by April and I

**Comment by JasonLovesDoggo** [comment]
> Member

see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
