### ISSUE TITLE
User API v3 change executive_of field

### ISSUE THREAD

**Issue by ji-mmyliu** [wlmac/metropolis#215]
(No rush at all, just making an issue so that you guys will remember it after I'm gone).

* Change `User` API field `organizations_leading` and `organizations` from number list to `Organization` list. Screenshot is attached:

![image](https://github.com/wlmac/metropolis/assets/70064220/f61798d7-1ffd-4b83-a935-2a467de68950)

**Comment by JasonLovesDoggo** [comment]
April and Daisy should be on it ™️
