### ISSUE TITLE
Allow users to change username/email

### ISSUE THREAD

**Issue by pinwheeeel** [wlmac/metropolis#275]
Was wondering if there's a reason why this feature isn't implemented.
Users should be able to change their username/email when editing their account settings.
If this idea goes through, is a cooldown for changing username/email a good idea?

**Comment by JasonLovesDoggo** [comment]
There isn't really any reason to allow people to change email as it has to be to be a tdsb email anyways, but as for username... It's supported by the API but-

**Comment by JasonLovesDoggo** [comment]
Username is fixed in #279 

Email's they can edit via https://maclyonsden.com/accounts/email/
