### ISSUE TITLE
Drop js-cookie dependency

### ISSUE THREAD

**Issue by fluix-dev** [wlmac/metropolis#35]
Pulling in an entire cookie handling library (js-cookie) for two calls seems a bit excessive:
https://github.com/wlmac/metropolis/blob/b18d6a1f346dc345ad77d25b08f74fa39da5f5f5/core/static/core/js/install.js#L7
https://github.com/wlmac/metropolis/blob/b18d6a1f346dc345ad77d25b08f74fa39da5f5f5/core/static/core/js/install.js#L30

No rush, but it wouldn't hurt to do one of the following at some point:
 1. Use the standard [`document.cookie`](https://developer.mozilla.org/en-US/docs/web/api/document/cookie) API.
 2. Use [`window.localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) for an API that's easier to work with.
 3. Use [Django sessions](https://docs.djangoproject.com/en/3.2/topics/http/sessions) to just store server-side.

**Comment by JasonLovesDoggo** [comment]
closed as this will essentially be fixed on switch to react UI
