### ISSUE TITLE
Pipe Things to External

### ISSUE THREAD

**Issue by nyiyui** [wlmac/metropolis#41]
Minimal support (title, link, image)

- [x] #62 
- [x] [Discord (embeds)](https://gitlab.com/mirukakoro/sisikyo/-/blob/9032cf7046bb46c6eb3752eb414a790b6756479b/feed/discord.go)
- [ ] Instagram (images)
- [ ] Facebook? (post+image?)
- [ ] RSS?
- [ ] Email?

**Comment by ApocalypseCalculator** [comment]
See branch og-tags

**Comment by colourdelete** [comment]
> See branch og-tags

Thanks; I'll change these:
- post URLs to use og-tags for things that can use it (e.g. Facebook) (might still use custom if it is better)
- since Instagram doesn't seem to support adding hyperlinks to posts, so will need a specific generator for that
