### ISSUE TITLE
Squished blog post banner on firefox mobile

### ISSUE THREAD

**Issue by hillcrestpaul0719** [wlmac/metropolis#51]
![image](https://user-images.githubusercontent.com/30064316/135732028-1f3ca173-3c47-4a8b-923c-9fe1dec0ed24.png)

**Comment by colourdelete** [comment]
[This](https://github.com/wlmac/metropolis/issues/51) *should* fix it (at least it did on desktop Firefox), can you try it please?

**Comment by hillcrestpaul0719** [comment]
Do you mean #38? If so, I haven't tested it yet. Sorry about that.

**Comment by colourdelete** [comment]
> Do you mean #38? 

Whooops sorry; yes that is correct; I've edited the answer.

**Comment by JasonLovesDoggo** [comment]
fixed.
