### ISSUE TITLE
Blog post order is confusing

### ISSUE THREAD

**Issue by hillcrestpaul0719** [wlmac/metropolis#53]
The time after the dot shows last modified, but sorted by created time.

![image](https://user-images.githubusercontent.com/30064316/135732082-ed0fce0e-c7c4-405a-8b58-a4b3c3680f34.png)

**Comment by colourdelete** [comment]
@hillcrestpaul0719 Should I order by `last_modified_date` or `created_date`?

**Comment by colourdelete** [comment]
Closign since #75 merged.
