### ISSUE TITLE
Add a forum

### ISSUE THREAD

**Issue by hillcrestpaul0719** [wlmac/metropolis#59]
- [x] #62

**Comment by colourdelete** [comment]
Also, IMO a good approach would be to use external software (e.g. Discourse) and SSO, since it keeps the main server code simple.

**Comment by JasonLovesDoggo** [comment]
@nyiyui title and content just match. What's the goal of this issue?

**Comment by nyiyui** [comment]
> title and content
What do you mean by that?

BTW, I think we're not doing this anymore (not many people want it)
