### ISSUE TITLE
Generate `*.ics` files

### ISSUE THREAD

**Issue by nyiyui** [wlmac/metropolis#77]
iCalendar files (`*.ics`) are a common format for calendars and is supported by Google Calendar, Microsoft Outlook, etc.

### Public Events

- [x] Generate public events ([public.ics](https://sisikyo.herokuapp.com/events/public.ics) on [public instance](https://sisikyo.herokuapp.com))
- [x] Put link to this in the website

Generates for public events using the `/api/events` endpoint.

### Private/User-specific Events

- [x] #62 
- [x] Generate user-specific events
- [x] Figure out how to securely authenticate user (the iCalendar URL may be accessed by other servers (eg Google servers))

URL format:
```
https://sisikyo.herokuapp.com/events/<opaque-key>/private.{ics,json,html}
```

Generates for user-specific events:
- Courses

**Comment by colourdelete** [comment]
Maybe like this?
`https://sisikyo.example.com/calendar.ics?oauth-code=…`
