### ISSUE TITLE
admin: in URL: `organization` → `club`

### ISSUE THREAD

**Issue by colourdelete** [wlmac/metropolis#78]

**Comment by colourdelete** [comment]
Sorry, @hillcrestpaul0719 do you mean rename API endpoints from `/api/organization*` to `/api/club*`?

**Comment by hillcrestpaul0719** [comment]
no i mean editing [this model](https://github.com/wlmac/metropolis/blob/master/core/models/organization.py#L60) to be shown as "Club URL" on the admin page
