### ISSUE TITLE
BCC Approval Emails to Site Owners

### ISSUE THREAD

**Issue by nyiyui** [wlmac/metropolis#84]
Site Owners:
- Official Metropolis Email?

- [x] Define "Site Owners" (assuming `setting.DEFAULT_FROM_EMAIL`)
- [x] Add Site Owners to BCC in all approval emails 37807db8dce05181d392e7ef0cf2c90ed9bfd976

**Comment by JasonLovesDoggo** [comment]
@nyiyui I belive this is done now (confirm?)

**Comment by nyiyui** [comment]
Sorry. Yes it's done.
